# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project. Settings here do _not_ act as
# defaults for all projects. To change Stack's default settings, edit
# '/root/.stack/config.yaml' instead.
#
# For more information about Stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-19.33
# resolver: lts-21.23 (ghc 9.4.8)
# resolver: lts-19.33 (ghc 9.0.2) # https://www.stackage.org/snapshots?page=7
# resolver: lts-18.28 (ghc 8.10.7)# https://www.stackage.org/snapshots?page=12
# compiler: ghc-9.0.2
# compiler-check: match-exact

allow-newer: true
allow-newer-deps: 
- ihaskell
- ihaskell-plot
- ihaskell-charts
- ihaskell-basic
- ihaskell-parsec
- ihaskell-gnuplot
- diagrams-cairo
- statestack
- Chart-cairo
- cairo 
- lens
- aeson
- ihaskell-diagrams
- ihaskell-blaze
# - ihaskell-display

# - ghc-syntax-highlighter
# - text
- hasktorch
- hasktorch-ffi-th
- dimension

extra-deps:
- ihaskell-0.10.2.2
- ipython-kernel-0.11.0.0
- ghc-parser-0.2.6.0


- plot-0.2.3.11
- cairo-0.13.10.0
- pango-0.13.10.0
- glib-0.13.10.0

- ihaskell-charts-0.3.0.0
- Chart-cairo-1.9

- ihaskell-diagrams-0.3.2.1
- diagrams-cairo-1.4.2.1
- statestack-0.3.1.1

- ihaskell-hatex-0.2.1.1
- ihaskell-juicypixels-1.1.0.1
- ihaskell-blaze-0.3.0.1

# - inline-r-1.0.0
# - ihaskell-parsec-0.2.1.0
